---
apiVersion: compute.gcp.crossplane.io/v1alpha1
kind: Firewall
metadata:
  name: brownbag
spec:
  forProvider:
    allowed:
      - IPProtocol: tcp
        ports: ["80", "443"]
      - IPProtocol: icmp
    sourceRanges: ["10.0.0.0/24"]
    networkRef:
      name: brownbag
  providerConfigRef:
    name: brownbag